---
deployment:
  tasks:
    # Set the deployment directory to the 'client' directory inside your repo
    - export DEPLOYMENT_DIR=${HOME}/CleanCode-Presentation-Website/client

    # Select the Node.js version (adjust if needed)
    - /bin/bash /opt/cpanel/ea-nodejs16/bin/nodejs select 16 --app CleanCode-Presentation-Website-client

    # Move into the 'client' directory
    - cd ${DEPLOYMENT_DIR}

    # Install only production dependencies
    - yarn install --production

    # Build the Next.js app
    - yarn build

    # Start the Next.js app
    - yarn start
