import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@style/globalStyle.scss";
import Script from "next/script";
import { I18nProvider } from './common/providers/I18nProvider';
import Navbar from "@components/Navbar";
import Footer from "@components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CleanCode Solutions",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    // apple: "/apple-touch-icon.png", TODO: add apple and android images
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-89H0W14JQN"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-89H0W14JQN');
        `}
        </Script>
      </head>
      <body className={inter.className}>
        <I18nProvider>
          <Navbar/>
            {children}
          <Footer/>
        </I18nProvider>
      </body>
    </html>
  );
}
