import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./style/globalStyle.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CleanCode Solutions",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
